{% set name = "typedframe" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/typedframe-{{ version }}.tar.gz
  sha256: 8a98dcf80c181120ff678477a6fdd05c9004f37d62f119511070ff3e621211c2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.7
  run:
    - numpy
    - pandas
    - python >=3.7

test:
  imports:
    - typedframe
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/areshytko/typedframe
  summary: Typed Wrappers over Pandas DataFrames with schema validation
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gabrielcnr
