{% set name = "typedframe" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/typedframe-{{ version }}.tar.gz
  sha256: d10eedb411e5a4d0cd91e5f280d35e4a559a69554e4eaad0ed7655672bcccbdb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.7
  run:
    - numpy
    - pandas
    - python >=3.7

test:
  imports:
    - typedframe
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/areshytko/typedframe
  summary: Typed Wrappers over Pandas DataFrames with schema validation
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gabrielcnr
